image: python:3.10.2-slim

stages:
  - test

before_script:
  - apt-get update && apt-get install -y sudo make curl git

test:
  stage: test
  script:
    - make prepare-dev
    - make compile-messages
    - make test

test-js-build-node14:
  image: node:14-bullseye-slim
  stage: test
  script:
    - cd js
    - npm install
    - npm run-script build -- -o /tmp/app.min.js

test-js-build-node16:
  image: node:16-bullseye-slim
  stage: test
  script:
    - cd js
    - npm install
    - npm run-script build -- -o /tmp/app.min.js

lint:
  stage: test
  script:
    - make prepare-dev
    - make lint
