stages:
  - lint
  - test
  - build
  - publish

include:
  - remote: "https://gitlab.nic.cz/turris/foris-controller/packages/-/raw/master/templates/python/base.yml"
  - remote: "https://gitlab.nic.cz/turris/foris-controller/packages/-/raw/master/templates/make/reforis.yml"
  - remote: "https://gitlab.nic.cz/turris/foris-controller/packages/-/raw/master/templates/python/build_and_publish.yml"


build::python:
  parallel:
    matrix:
      - IMAGE: ["registry.nic.cz/turris/foris-ci/reforis-ci"]

test::docs:
    stage: test
    image: "registry.nic.cz/turris/foris-ci/reforis-ci"
    script:
        - make prepare-dev
        - make prepare-docs
        - make docs

