image: python:3.7-slim-stretch

stages:
  - test

before_script:
  - apt-get update && apt-get -y install sudo make curl git

test:
  stage: test
  script:
    - make prepare-dev
    - make compile-messages
    - make test

test-js-build:
  image: node:12-bullseye-slim
  stage: test
  script:
    - cd js
    - npm install
    - npm run-script build -- -o /tmp/app.min.js
  

lint:
  stage: test
  script:
    - make prepare-dev
    - make lint
